### ISSUE TITLE
Project doesn't install necessary dependencies with pip install

### ISSUE THREAD

**Issue by bpepple** [pruizlezcano/comicgeeks#1]
Title pretty much explains it all, and it's fairly easy to check:

1. Use a virtualenv and install comicgeeks with pip.
2. In the virtualenv attempt to use comicgeeks and be presented with module missing errors.

If you grab the wheel file from PyPI, and inspect the contents you'll see the main deps aren't included. My guess is your build system is misconfigured, but since I've never used PyScaffold that is only a guess.

**Comment by pruizlezcano** [comment]
You were right. It should work in the new release.

Thanks!
